### ISSUE TITLE
Online & offline.

### ISSUE THREAD

**Issue by robinmg1** [Samsung/cordova-sectv-tizen#3]
Hi devs,
Recenlty I checked the new feature to know if network is online/offline, in orsay this works fine adding a listener window.addEventListener('online/offline', function() { });. But in tizen I notice that the event has been dispatched twice. So I checked the source code in "cordova-sectv-tizen/cordova-js-src/plugin/connection/proxy.js" and notice that you are calling webapis.network.addNetworkStateChangeListener(onChange) but in Tizen already fires online/offline event by default, so there is no need to add additional implementation for Tizen in general, including navigator.onLine.

Although the orsay platform is handling the online/offline properly the natvigator.onLine is not updated properly due the fact the TYPE of the connection remains the same event after the network is disconnected e.g. If the TV is connected through the Ethernet and we disconnect the cable the connection.TYPE still has ETHERNET status.

Thanks in advance.
Cheers!

**Comment by darangkim** [comment]
Hello Thank you for your concern.
We fixed the two issues.

As you told me, Tizen already fires online/offline event.
So, I deleted the duplicated code.

And We fixed the network TYPE issue.
Please check again in recently version.

Thank you.

**Comment by robinmg1** [comment]
Hi Darang,
I downloaded the update and works fine, but the property navigator.onLine is not working.
Although is enough the events online/offline to know network status, the flag of navigator.onLine should have the correct value.

For tizen, you don't need override this, because tizen already has this property in navigator (as online/offline events).

For orsay, could use a flag to give a correct value for navigator.onLine, because I check that you're using "return this.connection.type != 'none';". However on orsay, 'connection.type' is ethernet for online/offline case (when TV was connected wired), so navigator.onLine always is true.

Thanks for you help.

**Comment by darangkim** [comment]
Hello.

Sorry to late. We fixed network type issue.
You can check the navigator.onLine correctly.

If you have some additional questions, feel free to ask.
Thank you.
