### ISSUE TITLE
App in 720p media is not full screen.

### ISSUE THREAD

**Issue by robinmg1** [Samsung/cordova-sectv-tizen#4]
Hi there,
I'm working with a 720p app and I'm in troubles with full screen video and custom size container video on tizen platform.

-I have a viewport in index.html like this : <meta name="viewport" content="user-scalable=no, width=1280">
-So the document container is 1280x720, and my app are developed under this dimensions.
-Then I'm using media instance to display a video in fullscreen mode (setting 100% widht and height), but the video is displayed only in part of the screen, see the image > 
http://s2.subirimagenes.com/imagen/previo/thump_9570583screensize2.png

The issue only happens on tizen, I think this is because avplay rect always is displayed following 1080p resolution.

Also when I try to show a video in a small container with relative size to 720p resolution, same things happen, the video is smaller. (see image: http://s2.subirimagenes.com/imagen/previo/thump_9570578screensize1.png , blue is how should display and red how is displayed)

So I edit the next line code on toast.js to manage a ratio thinking in 720p app or less resolution and it works. This is the code fix:

**src/sectv-tizen/mediaProxy.js**
`containerStylecallbackFnTimer = setTimeout(function() {

```
if (MutationRecordProperty == 'style' && containerElem.childNodes[0]) {
    console.log('media::container style changed');

    var boundingRect = Util.getBoundingRect(containerElem);
    console.log('media:: DisplayRect left = '+boundingRect.left + ' | top = ' + boundingRect.top + ' | width = ' + boundingRect.width + ' | height = ' + boundingRect.height);
    containerElem.childNodes[0].style.left = boundingRect.left + 'px';
    containerElem.childNodes[0].style.top = boundingRect.top + 'px';
    containerElem.childNodes[0].style.width = boundingRect.width + 'px';
    containerElem.childNodes[0].style.height = boundingRect.height + 'px';

    var ratio = 1920/window.document.documentElement.clientWidth;
    boundingRect.left *= ratio;
    boundingRect.top *= ratio;
    boundingRect.width *= ratio;
    boundingRect.height *= ratio;
    setAvplayVideoRect(boundingRect);
}
```

},0);`

`containerAppendcallbackFnTimer = setTimeout(function() {

```
   if (MutationRecordProperty.addedNodes.length > 0) {
       if(hasContainerElem(MutationRecordProperty.addedNodes)) {
           console.log('media::container append');

           var boundingRect = Util.getBoundingRect(containerElem);
           console.log('media:: DisplayRect left = '+boundingRect.left + ' | top = ' + boundingRect.top + ' | width = ' + boundingRect.width + ' | height = ' + boundingRect.height);

           containerElem.childNodes[0].style.left = boundingRect.left + 'px';
            containerElem.childNodes[0].style.top = boundingRect.top + 'px';
            containerElem.childNodes[0].style.width = boundingRect.width + 'px';
            containerElem.childNodes[0].style.height = boundingRect.height + 'px';

            var ratio = 1920/window.document.documentElement.clientWidth;
            boundingRect.left *= ratio;
            boundingRect.top *= ratio;
            boundingRect.width *= ratio;
            boundingRect.height *= ratio;
            setAvplayVideoRect(boundingRect);
       }
   }
```

   },0);`

Thanks in advance.

Cheers!

**Comment by ghost** [comment]
Robin,
This is Sue. First, thank you for your concern.

Because base resolution of toast.media is 1920 \* 1080 regardless of app resolution,
this problem is occurred.

I checked this problem on my TV and I agree your opinion.
I think toast media resolution should be changed as app resolution.

I hope you contribute our cordova-sectv-tizen, but I will fix as your code on this time.
Next time, please contribute our TOAST. :D

Thanks.
Sue
